/* ============================================================================
   data.js — single source of truth for the Public Persuasion (MSC 482) dashboard
   Every page (index + week1..week5) reads from window.COURSE. Edit content HERE only.
   ----------------------------------------------------------------------------
   DUE-DATE RULE (applied in dashboard.js, not here):
     • `due` holds the REAL course date/deadline — the source of truth.
     • The dashboard DISPLAYS and SORTS by a personal target ONE DAY EARLIER,
       showing the real date beneath — EXCEPT items with dueType:'event'
       (fixed Zoom sessions), which always show their real date/time.
   dueType:  'deadline'    = hard due date
             'recommended' = syllabus "recommended completion" date
             'event'       = fixed live session (NO day-early shift)
   ----------------------------------------------------------------------------
   WEEK NUMBERS are the SYLLABUS calendar weeks (1–5). The lecture videos /
   instructor sometimes use a different (3-module) numbering; labels use weeks.
   `id` is the Supabase key — never change an id once it exists.
   ============================================================================ */
(function () {
  const CANVAS = 'https://canvas.northwestern.edu/courses/253939/';
  const OWN = 'You own this — no Canvas link';

  window.COURSE = {
    weeks: {
      1: { title: 'Notice the World, Influence the World',            range: 'Jul 26 – Aug 1'  },
      2: { title: 'Critical Thinking Through Private Writing',        range: 'Aug 2 – Aug 8'   },
      3: { title: 'Meaning & Audiences, Credibility & Color',         range: 'Aug 9 – Aug 15'  },
      4: { title: 'Moving People to Action with Logic & Emotion',     range: 'Aug 16 – Aug 22' },
      5: { title: 'Tips on Prepared Speech Delivery',                 range: 'Aug 23 – Aug 29' },
      6: { title: 'Finish Strong',                                   range: 'Aug 24 – Aug 27' },
    },

    items: [
      /* ── WEEK 1 ──────────────────────────────────────────────────────── (6) */
      { id:'w1-live1', week:1, type:'live',    material:'Course',        label:'Course Launch (Zoom recording)',
        url:'https://northwestern.zoom.us/rec/play/Fm9JzjgDYCjojEdSp95-pv5TzrCa5xSnAaW7zwVjggI2zCfHXWaVQLi3xbG7TmiBi-lNMzFzqKgJdUe2.oJbc3oCBV0DIgy4A',
        due:'2026-07-29T17:00:00-05:00', dueType:'event', required:true, note:'Recording · Wed Jul 29, 3:00 p.m. PT / 5:00 p.m. CT · Zoom ID 978 1643 3113',
        capture:'Course logistics + persuasion defined',
        date:'2026-07-29', whyOrder:'Orientation — sets expectations and the working definition of persuasion before anything else.', effort:75, mode:'move' },
      { id:'w1-r1',    week:1, type:'reading', material:'Week 1 Packet', label:'Week 1 Packet — pp. 1\u201316',
        url:'https://drive.google.com/file/d/1VFn6U24ci-1Nm5klvtywcdqF99g7ONSK/view?usp=drive_link', due:'2026-08-01', dueType:'deadline', required:true,
        capture:'Why words matter + noticing stance (pre-OCR)',
        date:'2026-07-29', whyOrder:'Foundational framing the two lectures then build on.', effort:30, mode:'desk' },
      { id:'w1-r2',    week:1, type:'reading', material:'Week 1 Packet', label:'Week 1 Packet — pp. 28\u201333',
        url:'https://drive.google.com/file/d/1VFn6U24ci-1Nm5klvtywcdqF99g7ONSK/view?usp=drive_link', due:'2026-08-01', dueType:'deadline', required:true,
        capture:'Need for order + language as sense-making',
        date:'2026-07-30', whyOrder:'These are the exact articles the \u201cIce Cream/Gettysburg\u201d lecture unpacks \u2014 read them together.', effort:15, mode:'desk' },
      { id:'w1-r3',    week:1, type:'reading', material:'Week 1 Packet', label:'Week 1 Packet — pp. 40\u201359',
        url:'https://drive.google.com/file/d/1VFn6U24ci-1Nm5klvtywcdqF99g7ONSK/view?usp=drive_link', due:'2026-08-01', dueType:'deadline', required:true,
        capture:'Language makes meaning + examples (pre-OCR)',
        date:'2026-07-31', whyOrder:'Rounds out the week once the core idea is in place.', effort:40, mode:'desk' },
      { id:'w1-lec1',  week:1, type:'lecture', material:'Lecture',       label:'Lecture 1 — Notice the World, Influence the World',
        url:CANVAS+'pages/lecture-1-notice-the-world-influence-the-world', due:'2026-08-01', dueType:'deadline', required:true,
        capture:'Persuasion as power + govern vs. inspire',
        date:'2026-07-30', whyOrder:"The course's thesis lecture \u2014 everything downstream builds on \u201cnotice the world \u2192 influence the world.\u201d", effort:30, mode:'move' },
      { id:'w1-lec2',  week:1, type:'lecture', material:'Lecture',       label:'Lecture 1 — Ice Cream, Google, and the Gettysburg Address',
        url:CANVAS+'pages/lecture-1-ice-cream-google-and-the-gettysburg-address', due:'2026-08-01', dueType:'deadline', required:true,
        capture:'Order from chaos + language makes meaning',
        date:'2026-07-30', whyOrder:'Answers the question Lecture 1 poses \u2014 what NEED does language fill? Pairs with the pp. 28\u201333 articles.', effort:30, mode:'move' },

      /* ── WEEK 2 ─────────────────────────────────────────────────────── (10) */
      { id:'w2-r1',    week:2, type:'reading', material:'Levy',          label:'Levy, Accidental Genius — pp. 1–128',
        url:'', due:'2026-08-04', dueType:'recommended', required:true, note:OWN,
        capture:'Right-brain technique + freedom/discipline',
        date:'2026-08-02', whyOrder:'Start this first — 128 pages, and the how-to workshop assumes you already know Levy\u2019s examples and metaphors.', effort:200, mode:'flex' },
      { id:'w2-r2',    week:2, type:'reading', material:'Week 1 Packet', label:'Week 1 Packet — pp. 60–83',
        url:'https://drive.google.com/file/d/1VFn6U24ci-1Nm5klvtywcdqF99g7ONSK/view?usp=drive_link', due:'2026-08-04', dueType:'recommended', required:true,
        capture:'Trust-decline stats + Pearce on leadership',
        date:'2026-08-02', whyOrder:'Lecture 2 Part 2 cites this packet by exact page number (64, 69) — read it before that lecture.', effort:45, mode:'desk' },
      { id:'w2-lec1',  week:2, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 1 — Critical Thinking Through Private Writing (Introduction)',
        url:CANVAS+'pages/lecture-2-part-1-critical-thinking-through-private-writing-introduction', due:'2026-08-04', dueType:'recommended', required:true,
        capture:'Conviction + connection defined',
        date:'2026-08-03', whyOrder:'Sets up the conviction/connection framework the whole week builds on, then sends you to the three speeches below.', effort:20, mode:'move' },
      { id:'w2-spk1',  week:2, type:'speech',  material:'Speech',        label:'MLK — I Have a Dream',
        url:CANVAS+'pages/martin-luther-king-jr-speech', due:'2026-08-04', dueType:'recommended', required:true, parentLecture:'w2-lec1',
        capture:'Conviction + delivered belief',
        date:'2026-08-03', whyOrder:'Lecture 1 pauses here and sends you to this clip first — watch right after, not later.', effort:5, mode:'move' },
      { id:'w2-spk2',  week:2, type:'speech',  material:'Speech',        label:'Oprah Winfrey speech',
        url:CANVAS+'pages/oprah-winfrey-speech', due:'2026-08-04', dueType:'recommended', required:true, parentLecture:'w2-lec1',
        capture:'Authenticity + speaking from within',
        date:'2026-08-03', whyOrder:'Second of the three conviction clips Lecture 1 sends you to.', effort:5, mode:'move' },
      { id:'w2-spk3',  week:2, type:'speech',  material:'Speech',        label:'Georgia Tech Freshman Convocation Speaker',
        url:CANVAS+'pages/georgia-tech-freshman-convocation-speaker-speech', due:'2026-08-04', dueType:'recommended', required:true, parentLecture:'w2-lec1',
        capture:'Unscripted conviction + a lesser-known speaker',
        date:'2026-08-03', whyOrder:'Third clip — a student speaker chosen specifically because conviction doesn\u2019t require fame.', effort:8, mode:'move' },
      { id:'w2-lec2',  week:2, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 2 — Critical Thinking Through Private Writing (Review)',
        url:CANVAS+'pages/lecture-2-part-2-critical-thinking-through-private-writing-review', due:'2026-08-04', dueType:'recommended', required:true,
        capture:'Why conviction now + belief\u2192action chain',
        date:'2026-08-03', whyOrder:'Continues directly from Lecture 1 — explains why conviction matters more today, then hands off to the workshop.', effort:20, mode:'move' },
      { id:'w2-lec3',  week:2, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 3 — Critical Thinking Through Private Writing (How To)',
        url:CANVAS+'pages/lecture-2-part-3-critical-thinking-through-private-writing-how-to', due:'2026-08-04', dueType:'recommended', required:true,
        capture:'Ten techniques + live writing drills',
        date:'2026-08-04', whyOrder:'A hands-on workshop, not a lecture to half-watch — actually do the writing exercises as they come up.', effort:60, mode:'desk' },
      { id:'w2-res1',  week:2, type:'resource', material:'Handout',      label:'Private Writing Handouts (for the How-To video)',
        url:CANVAS+'files/25220257?wrap=1', due:'2026-08-04', dueType:'recommended', required:true,
        capture:'Six handouts + prompt bank',
        date:'2026-08-04', whyOrder:'Keep this open during Lecture 3 — the workshop references these handouts by number throughout.', effort:10, mode:'desk' },
      { id:'w2-asg1',  week:2, type:'assignment', material:'Assignment', label:'Private Writing Assignment',
        url:CANVAS+'assignments/1796235', due:'2026-08-07T17:00:00-05:00', dueType:'deadline', required:true, note:'30 pts · ≤ 1 page',
        capture:'Session summary + technique used',
        date:'2026-08-06', whyOrder:'Needs at least one real private-writing session behind it — not just the workshop\u2019s 3-minute drills.', effort:45, mode:'desk' },

      /* ── WEEK 3 ─────────────────────────────────────────────────────── (17) */
      { id:'w3-live1', week:3, type:'live',    material:'Course',        label:'Live Discussion Session (Zoom)',
        url:'https://northwestern.zoom.us/j/96122965210?uname=Francis+Roberts#success',
        due:'2026-08-10T17:00:00-05:00', dueType:'event', required:true, note:'3:00–4:00 p.m. PT / 5:00–6:00 p.m. CT · Zoom ID 961 2296 5210',
        capture:'Live Q&A + peer discussion',
        date:'2026-08-10', whyOrder:'Fixed time — attend live if you can; a recording is usually posted after.', effort:60, mode:'move' },
      { id:'w3-r1',    week:3, type:'reading', material:'Cook',          label:'Cook — Chapters 1–5',
        url:'https://drive.google.com/file/d/1pd8_ctuicoDk5J2Yw4bkQgHOCNgrBKRs/view?usp=drive_link', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Audience biology + speech settings',
        date:'2026-08-09', whyOrder:'Fundamentals of knowing your audience and setting — read before the lectures build on organization and credibility.', effort:60, mode:'desk' },
      { id:'w3-r2',    week:3, type:'reading', material:'Cook',          label:'Cook — Chapter 9',
        url:'https://drive.google.com/file/d/1pd8_ctuicoDk5J2Yw4bkQgHOCNgrBKRs/view?usp=drive_link', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Six tone techniques + 9 rhetorical devices',
        date:'2026-08-12', whyOrder:'Pairs directly with the color/rhetorical-devices lectures — read alongside Lecture Parts 3–5.', effort:20, mode:'desk' },
      { id:'w3-r3',    week:3, type:'reading', material:'Week 2 Packet', label:'Week 2 Packet — pp. 1–12',
        url:'https://drive.google.com/file/d/1ZIxB-drC0SESuQAf2K13UhZ1XuZyBHFT/view?usp=drive_link', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Aristotle + ELM model + credibility',
        date:'2026-08-09', whyOrder:'Lecture Part 2 cites this by exact page number (28–30) for the Elaboration Likelihood Model — read first.', effort:25, mode:'desk' },
      { id:'w3-r4',    week:3, type:'reading', material:'Week 2 Packet', label:'Week 2 Packet — pp. 15–33',
        url:'https://drive.google.com/file/d/1ZIxB-drC0SESuQAf2K13UhZ1XuZyBHFT/view?usp=drive_link', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Organization rules + rhetorical devices',
        date:'2026-08-12', whyOrder:'The "be organized" writing rules and every device example (Churchill, Cuomo, MLK, FDR) the color lectures walk through.', effort:35, mode:'desk' },
      { id:'w3-res1',  week:3, type:'resource', material:'PowerPoint',   label:'Speechwriting: Credibility & Color (PowerPoint)',
        url:CANVAS+'files/25220239/download?wrap=1', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Slide reference + device checklist',
        date:'2026-08-12', whyOrder:'Keep open as a running reference across Lecture Parts 2–5.', effort:10, mode:'desk' },
      { id:'w3-lec1',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 1 — Moment & Meaning',
        url:CANVAS+'pages/lecture-part-1-moment-and-meaning', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Choose your meaning + see it to say it',
        date:'2026-08-11', whyOrder:'Opens the week\u2019s second chapter — moving from private conviction to public speechwriting.', effort:15, mode:'move' },
      { id:'w3-spk1',  week:3, type:'speech',  material:'Speech',        label:'Reagan — Challenger address',
        url:CANVAS+'pages/reagans-challenger-speech', due:'2026-08-15', dueType:'deadline', required:true, parentLecture:'w3-lec1',
        capture:'Speaking to five audiences at once',
        date:'2026-08-11', whyOrder:'Lecture 1 sends you here directly — the Noonan/Reagan case study the whole "moment" idea is built on.', effort:5, mode:'move' },
      { id:'w3-lec2',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 2 — Building Credibility',
        url:CANVAS+'pages/lecture-part-2-building-credibility', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Ethos/logos/pathos + competence vs. warmth',
        date:'2026-08-11', whyOrder:'Follows directly from the Reagan speech — introduces Aristotle\u2019s three appeals and the credibility framework.', effort:25, mode:'move' },
      { id:'w3-spk2',  week:3, type:'speech',  material:'Speech',        label:'Steve Jobs — Stanford commencement',
        url:CANVAS+'pages/steve-jobs-speech', due:'2026-08-15', dueType:'deadline', required:true, parentLecture:'w3-lec2',
        capture:'Roadmap + conversational credibility',
        date:'2026-08-11', whyOrder:'The lecture\u2019s example of "be organized, be a person" in practice — watch right after.', effort:5, mode:'move' },
      { id:'w3-lec3',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 3 — Adding Color with Pictures & Sounds (Introduced)',
        url:CANVAS+'pages/lecture-part-3-adding-color-with-pictures-and-sounds', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Vivid language + more words per thought',
        date:'2026-08-13', whyOrder:'Moves from the credibility foundation to the first color techniques — Churchill, then Reagan\u2019s Pointe du Hoc.', effort:15, mode:'move' },
      { id:'w3-spk3',  week:3, type:'speech',  material:'Speech',        label:'Mario Cuomo — 1984 DNC address',
        url:CANVAS+'pages/mario-cuomo-speech-video', due:'2026-08-15', dueType:'deadline', required:true, parentLecture:'w3-lec3',
        capture:'Counter-metaphor to Reagan\u2019s "shining city"',
        date:'2026-08-13', whyOrder:'Lecture 3 frames this as a direct rhetorical answer to Reagan\u2019s 1984 imagery — watch right after.', effort:8, mode:'move' },
      { id:'w3-lec4',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 4 — Adding Color with Pictures & Sounds (Continued)',
        url:CANVAS+'pages/lecture-part-4-adding-color-with-pictures-and-sounds', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Tricolon + repetition + quicken the pace',
        date:'2026-08-13', whyOrder:'Continues the device toolkit — the Devine/Apollo 13 extended metaphor, then rhythm-based devices.', effort:15, mode:'move' },
      { id:'w3-spk4',  week:3, type:'speech',  material:'Speech',        label:'Emma González speech',
        url:CANVAS+'pages/emma-gonzalez-speech', due:'2026-08-15', dueType:'deadline', required:true, parentLecture:'w3-lec4',
        capture:'Repetition, then a devastating pause',
        date:'2026-08-13', whyOrder:'The lecture\u2019s modern example of "quicken the pace" — watch right after Lecture 4.', effort:5, mode:'move' },
      { id:'w3-lec5',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 5 — Adding Color with Pictures & Sounds (Continued)',
        url:CANVAS+'pages/lecture-part-5-adding-color-with-pictures-and-sounds', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Rhetorical questions + rounding + pairs',
        date:'2026-08-14', whyOrder:'Finishes the device toolkit, then sends you to Jesse Jackson as a spot-the-technique exercise.', effort:12, mode:'move' },
      { id:'w3-spk5',  week:3, type:'speech',  material:'Speech',        label:'Jesse Jackson speech',
        url:CANVAS+'pages/jesse-jackson-speech', due:'2026-08-15', dueType:'deadline', required:true, parentLecture:'w3-lec5',
        capture:'Spot the devices, live',
        date:'2026-08-14', whyOrder:'An open exercise — try to name the alliteration, metaphor, and repetition as they happen.', effort:8, mode:'move' },
      { id:'w3-lec6',  week:3, type:'lecture', material:'Lecture',       label:'Lecture Part 6 — Recap of Moment & Meaning, Credibility & Color',
        url:CANVAS+'pages/lecture-part-6-recap-of-moment-and-meaning-credibility-and-color', due:'2026-08-15', dueType:'deadline', required:true,
        capture:'Full-week recap + preview of Week 4',
        date:'2026-08-14', whyOrder:'Ties every technique from this week together and previews next week\u2019s shift to logic and emotion.', effort:10, mode:'move' },

      /* ── WEEK 4 ─────────────────────────────────────────────────────── (13) */
      { id:'w4-r1',    week:4, type:'reading', material:'Cook',          label:'Cook — Chapter 10',
        url:'https://drive.google.com/file/d/1djjdHYOJaDgf1muytq3_m7HBKLBHj1ek/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true,
        capture:'Source credibility + argument + body language',
        date:'2026-08-18', whyOrder:'A genuinely different angle from the lectures — read this after both lectures to add real research depth.', effort:35, mode:'desk' },
      { id:'w4-r2',    week:4, type:'reading', material:'Week 3 Packet', label:'Week 3 Packet — pp. 1–35',
        url:'https://drive.google.com/file/d/1fg3hFWbmpi27hk7JhCSn62kJTXq5UQMg/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true,
        capture:'Fallacies + two-sided messaging + evidence',
        date:'2026-08-16', whyOrder:'Lecture 1 cites this by exact page (3–8 fallacies, 10–13 two-sided messaging, 13–24 evidence) — read before that lecture.', effort:40, mode:'desk' },
      { id:'w4-r3',    week:4, type:'reading', material:'Week 3 Packet', label:'Week 3 Packet — pp. 55–84',
        url:'https://drive.google.com/file/d/1fg3hFWbmpi27hk7JhCSn62kJTXq5UQMg/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true,
        capture:'Supporting material for emotional appeals',
        date:'2026-08-17', whyOrder:'Pairs with the emotional-appeals lectures — read alongside Lecture Parts 2–3.', effort:30, mode:'desk' },
      { id:'w4-r4',    week:4, type:'reading', material:'Week 3 Packet', label:'Week 3 Packet — pp. 88–103',
        url:'https://drive.google.com/file/d/1fg3hFWbmpi27hk7JhCSn62kJTXq5UQMg/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true,
        capture:'Supporting material for emotional appeals',
        date:'2026-08-17', whyOrder:'Continues the emotional-appeals supporting reading.', effort:16, mode:'desk' },
      { id:'w4-r5',    week:4, type:'reading', material:'Week 3 Packet', label:'Week 3 Packet — pp. 107–117',
        url:'https://drive.google.com/file/d/1fg3hFWbmpi27hk7JhCSn62kJTXq5UQMg/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true,
        capture:'Supporting material for emotional appeals',
        date:'2026-08-17', whyOrder:'Rounds out the emotional-appeals reading before Lecture Part 3.', effort:11, mode:'desk' },
      { id:'w4-r6',    week:4, type:'reading', material:'Luntz',         label:'Luntz, Words That Work — Ch. 1–4',
        url:'https://drive.google.com/file/d/1ghOad4F94ynlaVF8DBlCna74Kiie_hN6/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true, note:OWN,
        capture:'Ten Rules + message mistakes + reframing',
        date:'2026-08-18', whyOrder:'Chapters 1\u20134 build on each other: the Ten Rules, then how context/order/gender shape reception, then how word choice itself changes over time.', effort:60, mode:'flex' },
      { id:'w4-r7',    week:4, type:'reading', material:'Luntz',         label:'Luntz, Words That Work — Ch. 7–8',
        url:'https://drive.google.com/file/d/1ghOad4F94ynlaVF8DBlCna74Kiie_hN6/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true, note:OWN,
        capture:'Jack Welch + "death tax" + Contract with America',
        date:'2026-08-19', whyOrder:'Real corporate and political case studies applying the Ten Rules — read after Ch. 1\u20134.', effort:40, mode:'flex' },
      { id:'w4-r8',    week:4, type:'reading', material:'Luntz',         label:'Luntz, Words That Work — Ch. 10',
        url:'https://drive.google.com/file/d/1ghOad4F94ynlaVF8DBlCna74Kiie_hN6/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true, note:OWN,
        capture:'Tony Robbins + "common sense" as master frame',
        date:'2026-08-19', whyOrder:'Continues the case-study arc into the deeper values audiences respond to.', effort:20, mode:'flex' },
      { id:'w4-r9',    week:4, type:'reading', material:'Luntz',         label:'Luntz, Words That Work — Ch. 12',
        url:'https://drive.google.com/file/d/1ghOad4F94ynlaVF8DBlCna74Kiie_hN6/view?usp=drive_link', due:'2026-08-20', dueType:'recommended', required:true, note:OWN,
        capture:'21 words for the 21st century',
        date:'2026-08-19', whyOrder:'A practical closing reference — specific words Luntz argues will keep working.', effort:20, mode:'flex' },
      { id:'w4-res1',  week:4, type:'resource', material:'PowerPoint',   label:'Speechwriting: Logic, Emotion & Delivery Tips (PowerPoint)',
        url:CANVAS+'files/25220244/download?wrap=1', due:'2026-08-22', dueType:'recommended', required:true,
        capture:'Slide reference for the whole week',
        date:'2026-08-20', whyOrder:'Keep open as a running reference across all three lectures.', effort:10, mode:'desk' },
      { id:'w4-lec1',  week:4, type:'lecture', material:'Lecture',       label:'Lecture 1 — Using Logical Appeals',
        url:CANVAS+'pages/lecture-using-logical-appeals', due:'2026-08-22', dueType:'recommended', required:true,
        capture:'Facts + fallacies + resistant minds',
        date:'2026-08-20', whyOrder:'Opens the week — facts/numbers/organization, then the limits of logic (fallacies, ego-involvement).', effort:25, mode:'move' },
      { id:'w4-lec2',  week:4, type:'lecture', material:'Lecture',       label:'Lecture 1 — Using Emotional Appeals Part 1',
        url:CANVAS+'pages/lecture-using-emotional-appeals-part-1', due:'2026-08-22', dueType:'recommended', required:true,
        capture:'Stories + values + shared history',
        date:'2026-08-21', whyOrder:'Follows directly from logic\u2019s limits — where facts stop working, emotion picks up.', effort:25, mode:'move' },
      { id:'w4-lec3',  week:4, type:'lecture', material:'Lecture',       label:'Lecture 1 — Using Emotional Appeals Part 2',
        url:CANVAS+'pages/lecture-using-emotional-appeals-part-2', due:'2026-08-22', dueType:'recommended', required:true,
        capture:'Obama 2007 speech, fully annotated',
        date:'2026-08-21', whyOrder:'Closes the week with the Know/Feel/Do framework and a line-by-line worked example.', effort:20, mode:'move' },

      /* ── WEEK 5 ──────────────────────────────────────── (7 required + 1 opt) */
      { id:'w5-live1', week:5, type:'live',    material:'Course',        label:'Live Discussion Session (Zoom)',
        url:'https://northwestern.zoom.us/j/93394818258?uname=Francis+Roberts#success',
        due:'2026-08-24T17:00:00-05:00', dueType:'event', required:true, note:'3:00–4:00 p.m. PT / 5:00–6:00 p.m. CT · Zoom ID 933 9481 8258',
        capture:'Live Q&A + peer discussion',
        date:'2026-08-24', whyOrder:'Fixed time — a good place to ask about the speech assignment before it\u2019s due.', effort:60, mode:'move' },
      { id:'w5-r1',    week:5, type:'reading', material:'Cook',          label:'Cook — Chapter 7',
        url:'https://drive.google.com/file/d/1djjdHYOJaDgf1muytq3_m7HBKLBHj1ek/view?usp=drive_link', due:'2026-08-24', dueType:'recommended', required:true,
        capture:'Alarm reaction + coping with nerves',
        date:'2026-08-23', whyOrder:'Read before recording — concrete, research-backed techniques for the exact nerves you\u2019ll feel on camera.', effort:20, mode:'desk' },
      { id:'w5-lec1',  week:5, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 1 — Tips on Speech Delivery',
        url:CANVAS+'pages/lecture-2-tips-on-speech-delivery-part-1', due:'2026-08-24', dueType:'recommended', required:true,
        capture:'Conviction, connection, details + what we hear',
        date:'2026-08-23', whyOrder:'Opens with the delivery framework, then breaks down tone/volume/rate/pause/emphasis using Oprah\u2019s speech.', effort:20, mode:'move' },
      { id:'w5-lec2',  week:5, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 2 — Tips on Speech Delivery',
        url:CANVAS+'pages/lecture-2-tips-on-speech-delivery-part-2', due:'2026-08-24', dueType:'recommended', required:true,
        capture:'Gestures, body language, nerves, eye contact',
        date:'2026-08-23', whyOrder:'Live demonstration of gestures and stance, plus the most direct reassurance in the course about nerves.', effort:15, mode:'move' },
      { id:'w5-lec3',  week:5, type:'lecture', material:'Lecture',       label:'Lecture 2 Part 3 — Tips on Speech Delivery',
        url:CANVAS+'pages/lecture-2-tips-on-speech-delivery-part-3', due:'2026-08-24', dueType:'recommended', required:true,
        capture:'Full recap + marking up your script',
        date:'2026-08-23', whyOrder:'Ties everything together and explains exactly why the script is due a day before the video.', effort:10, mode:'move' },
      { id:'w5-asg1',  week:5, type:'assignment', material:'Assignment', label:'Persuasive Policy Speech — Part 1 (written script)',
        url:CANVAS+'assignments/1796233', due:'2026-08-26T17:00:00-05:00', dueType:'deadline', required:true, note:'40 pts · 5–6 min',
        capture:'Full written script + named audience',
        date:'2026-08-25', whyOrder:'Due first on purpose — you need at least a day to mark up the text before recording Part 2.', effort:150, mode:'desk' },
      { id:'w5-asg2',  week:5, type:'assignment', material:'Assignment', label:'Persuasive Policy Speech — Part 2 (video delivery)',
        url:CANVAS+'assignments/1796234', due:'2026-08-27T17:00:00-05:00', dueType:'deadline', required:true, note:'30 pts · 4–5 min',
        capture:'Recorded delivery of the same speech',
        date:'2026-08-26', whyOrder:'Record after living with the marked-up script for a day — never deliver it "hot off the printer."', effort:60, mode:'desk' },
      { id:'w5-disc1', week:5, type:'assignment', material:'Assignment', label:'Persuasive Policy Speech — discussion post',
        url:CANVAS+'discussion_topics/1855997', due:'2026-08-27', dueType:'recommended', required:false, note:'Optional · ungraded',
        capture:'Optional peer sharing',
        date:'2026-08-27', whyOrder:'Purely optional — share your Arc Studio recording with classmates if you\u2019d like, no grading impact.', effort:5, mode:'flex' },

      /* ── FINISH PLAN (week 6) ─────────────────────── (17 new · 8 shared) ──
         These are execution steps for the final four days, NOT syllabus items.
         They are surfaced by finish.html via COURSE.plan below, which also
         reuses eight existing Week 4/5 items by id so state stays shared.     */
      { id:'w6-m4',    week:6, type:'task',    material:'Monday, Aug 24',      label:'12-minute timed write — no editing, no backspacing',
        url:'', due:'2026-08-24', dueType:'deadline', required:true, note:OWN,
        capture:'Raw material, not decisions',
        date:'2026-08-24', whyOrder:'The Levy method from Week 2. Placed after the lectures so you start with input rather than a blank page.', effort:12, mode:'desk' },
      { id:'w6-m5',    week:6, type:'task',    material:'Monday, Aug 24',      label:'Write one sentence: "I want to persuade ___ that ___"',
        url:'', due:'2026-08-24', dueType:'deadline', required:true, note:OWN,
        capture:'Topic + named audience',
        date:'2026-08-24', whyOrder:'The only Monday deliverable. Everything Tuesday depends on this sentence existing.', effort:3, mode:'desk' },

      { id:'w6-t1',    week:6, type:'task',    material:'Tuesday, Aug 25',     label:'Cook Ch. 4 — persuasive-structure section only',
        url:'https://drive.google.com/file/d/1pd8_ctuicoDk5J2Yw4bkQgHOCNgrBKRs/view?usp=drive_link', due:'2026-08-25', dueType:'deadline', required:true,
        note:'Partial read of the material in w3-r1 (Cook, Ch. 1–5) — the Ch. 4 structure section only, tracked separately.',
        capture:"Problem/solution + Monroe's Motivated Sequence + indirect proof",
        date:'2026-08-25', whyOrder:'Gives you a skeleton to draft into instead of inventing structure mid-draft.', effort:15, mode:'desk' },
      { id:'w6-t3',    week:6, type:'task',    material:'Tuesday, Aug 25',     label:"Re-skim Week 2 Packet — DeSanto's own handouts",
        url:'https://drive.google.com/file/d/1ZIxB-drC0SESuQAf2K13UhZ1XuZyBHFT/view?usp=drive_link', due:'2026-08-25', dueType:'deadline', required:true,
        note:'Already completed as w3-r3 / w3-r4; this is a re-skim, tracked separately.',
        capture:'Roadmap and sign-posting + conversational word swaps',
        date:'2026-08-25', whyOrder:'His structural checklist in his own words — faster to reload than to rederive.', effort:10, mode:'desk' },
      { id:'w6-t4',    week:6, type:'task',    material:'Tuesday, Aug 25',     label:'Pick your structure — Monroe, problem/solution, or indirect proof',
        url:'', due:'2026-08-25', dueType:'deadline', required:true, note:OWN,
        capture:'One choice, written down',
        date:'2026-08-25', whyOrder:'Deciding structure mid-draft turns a two-hour draft into a five-hour one.', effort:5, mode:'flex' },
      { id:'w6-t5',    week:6, type:'task',    material:'Tuesday, Aug 25',     label:'Draft start to finish — one pass, no editing',
        url:'', due:'2026-08-25', dueType:'deadline', required:true, note:OWN,
        capture:'700–850 words, complete, allowed to be bad',
        date:'2026-08-25', whyOrder:'A finished bad draft today beats a perfect first paragraph tomorrow.', effort:120, mode:'desk' },

      { id:'w6-w1',    week:6, type:'task',    material:'Wednesday, Aug 26',   label:'Read the whole draft aloud with a stopwatch',
        url:'', due:'2026-08-26', dueType:'deadline', required:true, note:OWN,
        capture:'Actual runtime, before you touch a word',
        date:'2026-08-26', whyOrder:'Timing tells you what to cut more reliably than judgment does.', effort:10, mode:'move' },
      { id:'w6-w2',    week:6, type:'task',    material:'Wednesday, Aug 26',   label:'Cut to time — whole ideas, not adjectives',
        url:'', due:'2026-08-26', dueType:'deadline', required:true, note:OWN,
        capture:'Target 5:15–5:45',
        date:'2026-08-26', whyOrder:'5–6 minutes confirmed by DeSanto at the Aug 24 live session.', effort:30, mode:'desk' },
      { id:'w6-w4',    week:6, type:'task',    material:'Wednesday, Aug 26',   label:'Read aloud again — fix every stumble',
        url:'', due:'2026-08-26', dueType:'deadline', required:true, note:OWN,
        capture:'Anything hard to say gets rewritten',
        date:'2026-08-26', whyOrder:'Written-sounding sentences are the most common thing that wrecks a delivery.', effort:10, mode:'move' },
      { id:'w6-w6',    week:6, type:'task',    material:'Wednesday, Aug 26',   label:'Print the script in Cook Ch. 6 format',
        url:'', due:'2026-08-26', dueType:'deadline', required:true, note:OWN,
        capture:'Large type + top two-thirds only + complete sentence per page',
        date:'2026-08-26', whyOrder:'Keeps your chin from dropping mid-sentence on camera.', effort:15, mode:'desk' },

      { id:'w6-h2',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Mark up the printed script',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:'Underline emphasis + mark pauses + note eye-contact points',
        date:'2026-08-27', whyOrder:'Never deliver a blank text hot off the printer.', effort:20, mode:'desk' },
      { id:'w6-h3',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Rehearse in thirds',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:'What am I communicating here, and what delivery does that?',
        date:'2026-08-27', whyOrder:'Section-by-section beats full run-throughs for fixing specific problems.', effort:30, mode:'move' },
      { id:'w6-h4',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Memorize the first 15 seconds and the last 15 seconds',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:'Open under duress + always exit gracefully',
        date:'2026-08-27', whyOrder:"Cook's rule — the opening is hardest and the close is what they remember.", effort:10, mode:'move' },
      { id:'w6-h5',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Set up — camera at eye level, lighting and audio test',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:'15-second test clip before the real take',
        date:'2026-08-27', whyOrder:'Discovering bad audio after take three is the worst possible time.', effort:10, mode:'flex' },
      { id:'w6-h6',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Record — three takes maximum',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:"State your audience's identity before you begin speaking",
        date:'2026-08-27', whyOrder:'Required by the assignment. Take three ships regardless.', effort:30, mode:'move' },
      { id:'w6-h7',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'Watch your own take back against the delivery criteria',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:'Tone, pace, pauses, eye contact, gestures',
        date:'2026-08-27', whyOrder:'This rep only exists this week and never again.', effort:15, mode:'flex' },
      { id:'w6-h9',    week:6, type:'task',    material:'Thursday, Aug 27',    label:'20-minute debrief — what was hard and why',
        url:'', due:'2026-08-27', dueType:'deadline', required:true, note:OWN,
        capture:"One page, unpolished, written while it's raw",
        date:'2026-08-27', whyOrder:'Makes every post-course reading answer a question you actually have.', effort:20, mode:'desk' },
    ],

    /* ── FINISH PLAN ─────────────────────────────────────────────────────────
       Ordered day-by-day execution list rendered by finish.html (week 6).
       Each entry is an `id` into COURSE.items above — existing Week 4/5 ids are
       reused deliberately so checking a step on finish.html checks it on that
       week's page too (one Supabase row, one source of truth).
       `whyOrder` here is an OPTIONAL per-plan override, used only where a shared
       item's own whyOrder was written for its original week and reads wrong in
       this day sequence. dashboard.js merges it onto a COPY — it never mutates
       the object in COURSE.items, so the week pages keep their own wording.
       Each day's `date` is applied to its steps as the "Best timing" value and
       is what the checklist's by-date grouping keys on.                        */
    plan: [
      { day: 'Monday, Aug 24', date: '2026-08-24', entries: [
        { id:'w5-lec1', whyOrder:"Zero prerequisites — you don't need a topic to watch this, which makes it the lowest-friction way to start." },
        { id:'w5-lec2', whyOrder:"Continues Part 1, and it's the most direct reassurance in the course about nerves." },
        { id:'w5-lec3', whyOrder:"Covers marking up a script, which gives Thursday's markup step its rationale before you've written anything." },
        { id:'w6-m4' },
        { id:'w6-m5' },
      ]},
      { day: 'Tuesday, Aug 25', date: '2026-08-25', entries: [
        { id:'w6-t1' },
        { id:'w4-r1',  whyOrder:'The only assigned text no lecture ever references — verified across all sixteen transcripts. Highest-value unread material you have, and checking it here also clears it from your Week 4 backlog.' },
        { id:'w6-t3' },
        { id:'w6-t4' },
        { id:'w6-t5' },
      ]},
      { day: 'Wednesday, Aug 26', date: '2026-08-26', entries: [
        { id:'w6-w1' },
        { id:'w6-w2' },
        { id:'w4-r9',  whyOrder:'Use it as a revision tool, not a read — swap flat words while the structure is already fixed. Also clears a Week 4 backlog item.' },
        { id:'w6-w4' },
        { id:'w5-asg1', whyOrder:'Submit by 2:00 p.m. PT. The real deadline is 3:00 p.m. PT / 5:00 p.m. CT — the hour of buffer is non-negotiable.' },
        { id:'w6-w6' },
      ]},
      { day: 'Thursday, Aug 27', date: '2026-08-27', entries: [
        { id:'w5-r1',  whyOrder:'Read before you rehearse, not after — it changes how you rehearse.' },
        { id:'w6-h2' },
        { id:'w6-h3' },
        { id:'w6-h4' },
        { id:'w6-h5' },
        { id:'w6-h6' },
        { id:'w6-h7' },
        { id:'w5-asg2', whyOrder:'Submit by 2:00 p.m. PT. Confirm processing finished before closing the tab.' },
        { id:'w6-h9' },
      ]},
    ],
  };
})();
